-- 코드를 입력하세요
SELECT UB.TITLE, 
UB.BOARD_ID, 
UR.REPLY_ID, 
UR.WRITER_ID, 
UR.CONTENTS, 
TO_CHAR(UR.CREATED_DATE, 'yyyy-mm-dd') as CREATED_DATE
FROM USED_GOODS_BOARD UB, USED_GOODS_REPLY UR
WHERE UB.BOARD_ID = UR.BOARD_ID
    AND TO_CHAR(UB.CREATED_DATE, 'yyyy-mm') = '2022-10'
ORDER BY UR.CREATED_DATE,
        UB.TITLE;